abstract: simple converter of geo coordinates
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Geo-Coordinates-Converter
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Readonly: 0
  Storable: 0
  String::CamelCase: 0
  UNIVERSAL::require: 0
version: 0.03
